version: "3.9"

services:
  frontend-react:
    build:
      context: ./WEBClient
      dockerfile: front.Dockerfile
    image: IDP2022/frontend
    networks:
      - frontend
  backend:
    build:
      context: .
      dockerfile: back.Dockerfile
    image: IDP2022/backend
    networks:
      - frontend
      - backend
  db:
    image: IDP2022/db
    networks:
      - backend

networks:
  frontend:
  backend: