version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Gigel12345"
    ports:
      - "1433:1433"

  proiect_pweb.api:
    image: backend/v1
    build:
      context: .
      dockerfile: WEBClient\Dockerfile
    depends_on:
      - db