// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proiect_PWEB.Infrastructure.Models_Generate
{
    public partial class Country
    {
        public Country()
        {
            Request = new HashSet<Request>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Request> Request { get; set; }
    }
}